#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Regenerate the cross-language contracts from the API's Pydantic models.
#
#   scripts/gen-contracts.sh           write contracts/schemas, canonical contracts/fixtures and ui/src/generated
#   scripts/gen-contracts.sh --check   change nothing; exit 1 if any of them is out of date (CI)
#
# Needs uv and Node.js (for npx).
set -euo pipefail

# Pinned so the generated TypeScript is reproducible.
readonly JSON2TS=json-schema-to-typescript@16.0.0
readonly PRETTIER=prettier@3.9.9
readonly BANNER='/* Generated by scripts/gen-contracts.sh from contracts/. Do not edit. */'

root="$(cd "$(dirname "$0")/.." && pwd)"

check=false
case "${1-}" in
  "") ;;
  --check) check=true ;;
  *)
    echo "usage: $0 [--check]" >&2
    exit 2
    ;;
esac

# In --check mode, generate into a scratch copy and compare it with the tree.
out="$root"
if "$check"; then
  out="$(mktemp -d)"
  trap 'rm -rf "$out"' EXIT
  mkdir -p "$out/contracts"
  cp -R "$root/contracts/fixtures" "$out/contracts/fixtures"
fi

generated="$out/ui/src/generated"
rm -rf "$out/contracts/schemas" "$generated"
mkdir -p "$generated"

# Pydantic -> contracts/schemas/*.schema.json; validate and canonicalize contracts/fixtures/*.json.
uv run --project "$root/api" --locked --quiet python -m demo_api.contracts "$out/contracts"

# JSON Schema -> TypeScript, plus the tool registry as a typed constant.
node_tool() {
  npx --yes --package "$JSON2TS" --package "$PRETTIER" -- "$@"
}
to_typescript() {
  node_tool json2ts --input "$1" --output "$2" --bannerComment "$BANNER" --maxItems=-1 --no-format
}
to_typescript "$out/contracts/schemas/execution-event.schema.json" "$generated/execution-event.ts"
to_typescript "$out/contracts/schemas/receipt.schema.json" "$generated/receipt.ts"
to_typescript "$root/contracts/tool-registry.schema.json" "$generated/tool-registry.ts"
printf '\nexport const TOOL_REGISTRY: ToolRegistry = %s\n' "$(cat "$root/contracts/tool-registry.json")" \
  >>"$generated/tool-registry.ts"

# Format in the style of ui/.prettierrc (without its Tailwind plugin, which only sorts class names).
node_tool prettier --no-config --no-semi --single-quote --print-width 100 --trailing-comma es5 \
  --log-level warn --write "$generated"

if "$check"; then
  stale=0
  for dir in contracts/schemas contracts/fixtures ui/src/generated; do
    diff -ru "$root/$dir" "$out/$dir" || stale=1
  done
  if [ "$stale" -ne 0 ]; then
    echo "Contracts are out of date: run scripts/gen-contracts.sh and commit the result." >&2
    exit 1
  fi
  echo "Contracts are up to date."
fi
